"""add risk_type to violations

Revision ID: c0f442a246a3
Revises: c762b5e3fbd7
Create Date: 2026-08-17 15:16:52.379137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f442a246a3'
down_revision: Union[str, Sequence[str], None] = 'c762b5e3fbd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_reports', sa.Column('risk_type', sa.String(), nullable=True))
    op.add_column('violations', sa.Column('risk_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violations', 'risk_type')
    op.drop_column('incident_reports', 'risk_type')
    # ### end Alembic commands ###
