// ══════════════════════════════════════════
// pages/Reports.jsx
// ══════════════════════════════════════════
import { useState, useEffect } from 'react'
import { reportsAPI } from '../api/client'

export default function Reports() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [selected, setSelected] = useState(null)

  useEffect(() => {
    reportsAPI.getAll()
      .then((r) => setReports(r.data))
      .finally(() => setLoading(false))
  }, [])

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold text-gray-800">Incident Reports</h1>

      {loading ? (
        <div className="text-center py-12 text-gray-400">Loading...</div>
      ) : reports.length === 0 ? (
        <div className="text-center py-12">
          <p className="text-gray-400 mb-2">No reports yet</p>
          <p className="text-gray-300 text-sm">
            Reports are auto-generated by the T5 engine after violations
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-3 gap-4">
          {/* Report list */}
          <div className="col-span-1 space-y-2">
            {reports.map((r) => (
              <div
                key={r.id}
                onClick={() => setSelected(r)}
                className={`cursor-pointer rounded-lg p-3 border transition ${
                  selected?.id === r.id
                    ? 'border-yellow-400 bg-yellow-50'
                    : 'border-gray-200 bg-white hover:border-gray-300'
                }`}
              >
                <p className="font-semibold text-gray-800 text-sm">
                  Report #{r.id}
                </p>
                <p className="text-gray-500 text-xs mt-1">
                  {new Date(r.created_at).toLocaleDateString()}
                </p>
                <span className="text-xs bg-gray-100 text-gray-600 px-2 py-1 rounded mt-1 inline-block">
                  {r.generated_by}
                </span>
              </div>
            ))}
          </div>

          {/* Report detail */}
          <div className="col-span-2 bg-white rounded-xl shadow p-6">
            {selected ? (
              <>
                <h2 className="text-lg font-bold text-gray-800 mb-4">
                  Report #{selected.id}
                </h2>
                <p className="text-gray-500 text-sm mb-4">
                  Generated: {new Date(selected.created_at).toLocaleString()}
                </p>
                <div className="bg-gray-50 rounded-lg p-4 text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                  {selected.summary_text}
                </div>
              </>
            ) : (
              <div className="flex items-center justify-center h-full text-gray-400">
                Select a report to view details
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}